<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pov</string>
	</array>
	<key>name</key>
	<string>POV-Ray</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.povray</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.povray</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.povray</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.povray</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(rotate|scale|translate)\b</string>
			<key>name</key>
			<string>keyword.transformation.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(transform)\b</string>
			<key>name</key>
			<string>keyword.transform.transformation.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(inverse)\b</string>
			<key>name</key>
			<string>keyword.transform-item.transformation.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(matrix)\b</string>
			<key>name</key>
			<string>keyword.matrix.transformation.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(camera)\b</string>
			<key>name</key>
			<string>keyword.camera.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(perspective|orthographic|fisheye|ultra_wide_angle|omnimax|panoramic|cylinder|spherical)\b</string>
			<key>name</key>
			<string>keyword.camera-type.camera.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(location|right|up|direction|sky)\b</string>
			<key>name</key>
			<string>keyword.camera-vector.camera.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(angle|look_at|blur_amples|aperture|focal_point|confidence|variance)\b</string>
			<key>name</key>
			<string>keyword.camera-modifier.camera.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|no|off|on|pi|true|yes)\b</string>
			<key>name</key>
			<string>constant.float-expression.built-in.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(x|y|z|t|u|v)\b</string>
			<key>name</key>
			<string>constant.vector-built-in-ident.built-in.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abs|acos|acosh|asc|asin|asinh|atan|atanh|atan2|ceil|cos|cosh|defined|degrees|dimensions|dimension_size|div|exp|file_exists|floor|int|ln|log|max|min|mod|pow|radians|rand|seed|select|sin|sinh|sqrt|strcmp|strlen|tan|tanh|val|vdot|vlength)\b</string>
			<key>name</key>
			<string>entity.float-function.built-in.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(min_extent|max_extent|trace|vaxis_rotate|vcross|vrotate|vnormalize|vturbulence)\b</string>
			<key>name</key>
			<string>entity.vector-function.built-in.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(clock|clock_delta|clock_on|final_clock|final_frame|frame_number|initial_clock|initial_frame)\b</string>
			<key>name</key>
			<string>variable.float-built-in-ident.built-in.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(color)\b</string>
			<key>name</key>
			<string>storage.color.built-in.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(rgb|rgbf|rgbt|rgbft)\b</string>
			<key>name</key>
			<string>keyword.color-vector.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(red|blue|green|filter|transmit)\b</string>
			<key>name</key>
			<string>keyword.color-keyword-item.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(str|concat|chr|substr|strupr|strlwr|vstr)\b</string>
			<key>name</key>
			<string>entity.string-function.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(#declare|#local)\b</string>
			<key>name</key>
			<string>keyword.declartio.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(#undef)\b</string>
			<key>name</key>
			<string>keyword.destroying.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(#fopen)\b</string>
			<key>name</key>
			<string>keyword.fopen-directive.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(read|write|append)\b</string>
			<key>name</key>
			<string>constant.open-type.fopen-directive.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(#fclose)\b</string>
			<key>name</key>
			<string>keyword.fclose-directive.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(#read)\b</string>
			<key>name</key>
			<string>keyword.read-directive.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(#write)\b</string>
			<key>name</key>
			<string>keyword.write-directive.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(#default)\b</string>
			<key>name</key>
			<string>keyword.default-directive.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(#version)\b</string>
			<key>name</key>
			<string>keyword.version-directive.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(#if|#else|#ifdef|#ifndef|#switch|#case|#range|#break|#while|#end|#macro)\b</string>
			<key>name</key>
			<string>keyword.conditional-directive.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(#debug|#error|#warning)\b</string>
			<key>name</key>
			<string>keyword.text-stream-directive.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(spline)\b</string>
			<key>name</key>
			<string>keyword.spline.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(linear_spline|quadratic_spline|cubic_spline|natural_spline)\b</string>
			<key>name</key>
			<string>keyword.spline-type.spline.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(object)\b</string>
			<key>name</key>
			<string>keyword.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(blob|sphere|cylinder|threshold|hierarchy|sturm)\b</string>
			<key>name</key>
			<string>keyword.blob.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(box)\b</string>
			<key>name</key>
			<string>keyword.box.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cone)\b</string>
			<key>name</key>
			<string>keyword.cone.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cylinder)\b</string>
			<key>name</key>
			<string>keyword.cylinder.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(height_field|function|hierarchy|smooth|water_level)\b</string>
			<key>name</key>
			<string>keyword.height-field.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(julia_fractal|max_iteration|precision|slice|quaternion|hypercomplex|sqr|cube|exp|reciprocal|sin|asin|sinh|asinh|cos|acos|cosh|acosh|tan|atan|tanh|atanh|ln|pwr)\b</string>
			<key>name</key>
			<string>keyword.julia-fractal.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(lathe|linear_spline|quadratic_spline|cubic_spline|bezier_spline|sturm)\b</string>
			<key>name</key>
			<string>keyword.lathe.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(prism|linear_spline|quadratic_spline|cubic_spline|bezier_spline|linear_sweep|conic_sweep|sturm)\b</string>
			<key>name</key>
			<string>keyword.prism.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sphere)\b</string>
			<key>name</key>
			<string>keyword.sphere.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sphere_sweeep|linear_spline|b_spline|cubic_spline|tolerance)\b</string>
			<key>name</key>
			<string>keyword.sphere-sweeep.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(superellipsoid)\b</string>
			<key>name</key>
			<string>keyword.superellipsoid.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sor|sturm)\b</string>
			<key>name</key>
			<string>keyword.sor.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(text|ttf)\b</string>
			<key>name</key>
			<string>keyword.text.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(torus|sturm)\b</string>
			<key>name</key>
			<string>keyword.torus.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bicubic_patch|type|u_steps|v_steps|flatness)\b</string>
			<key>name</key>
			<string>keyword.bicubic_patch.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(disc)\b</string>
			<key>name</key>
			<string>keyword.disc.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(mesh|triangle|uv_vectors|smooth_triangle|texture|texture_list|inside_vector|hierarchy)\b</string>
			<key>name</key>
			<string>keyword.mesh.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(mesh2|vertex_vectors|normal_vectors|uv_vectors|texture_list|face_indices|normal_indices|uv_indices|inside_vector)\b</string>
			<key>name</key>
			<string>keyword.mesh2.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(polygon)\b</string>
			<key>name</key>
			<string>keyword.polygon.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(triangle)\b</string>
			<key>name</key>
			<string>keyword.triangle.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(smooth_triangle)\b</string>
			<key>name</key>
			<string>keyword.smooth_triangle.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(plane)\b</string>
			<key>name</key>
			<string>keyword.plane.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(poly|sturm)\b</string>
			<key>name</key>
			<string>keyword.poly.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cubic)\b</string>
			<key>name</key>
			<string>keyword.cubic.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(quartic)\b</string>
			<key>name</key>
			<string>keyword.quartic.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(quadric)\b</string>
			<key>name</key>
			<string>keyword.quadric.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(isosurface|function|contained_by|threshold|accuracy|max_gradient|evaluate|open|max_trace|all_intersections)\b</string>
			<key>name</key>
			<string>keyword.isosurface.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(parametric|function|contained_by|max_gradient|accuracy|precompute)\b</string>
			<key>name</key>
			<string>keyword.parametric.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(smooth_triangle)\b</string>
			<key>name</key>
			<string>keyword.smooth_triangle.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(union|split_union)\b</string>
			<key>name</key>
			<string>keyword.union.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(intersection)\b</string>
			<key>name</key>
			<string>keyword.intersection.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(difference)\b</string>
			<key>name</key>
			<string>keyword.difference.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(merge)\b</string>
			<key>name</key>
			<string>keyword.merge.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(light_source|spotlight|shadowless|cylinder|parallel|radius|falloff|tightness|point_at|area_light|adaptive|jitter|circular|orient|looks_like|fade_distance|fade_power|media_attenuation|media_interaction|projected_through)\b</string>
			<key>name</key>
			<string>keyword.light-source.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(light_group|light_source|global_lights)\b</string>
			<key>name</key>
			<string>keyword.light-group.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(clipped_by|bounded_by|no_shadow|noimage|no_reflection|inverse|sturm|hierarchy|double_illuminate|hollow|interior|material|texture|interior_texture|photons|pigment|normal|finish)\b</string>
			<key>name</key>
			<string>keyword.object-modifier.object.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(pigment)\b</string>
			<key>name</key>
			<string>keyword.pigment.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(image_map)\b</string>
			<key>name</key>
			<string>keyword.pigment-type.pigment.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(color_map|colour_map|pigment_map|quick_color)\b</string>
			<key>name</key>
			<string>keyword.pigment_modifier.pigment.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(checker|hexagon|brick|object)\b</string>
			<key>name</key>
			<string>keyword.color-list.pigment.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(map_type|once|interpolate|filter|transmit)\b</string>
			<key>name</key>
			<string>keyword.image-map.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(gif|tga|iff|ppm|pgm|png|jpeg|tiff|sys)\b</string>
			<key>name</key>
			<string>keyword.bitmap-type.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(normal)\b</string>
			<key>name</key>
			<string>keyword.normal.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(normal_map|slope_map|bump_size|no_bump_scale|accuracy)\b</string>
			<key>name</key>
			<string>keyword.normal-modifier.normal.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bump_map)\b</string>
			<key>name</key>
			<string>keyword.bump-map.normal.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(map_type|once|interpolate|use_color|use_colour|bump_size)\b</string>
			<key>name</key>
			<string>keyword.bump-map-mod.normal.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(finish)\b</string>
			<key>name</key>
			<string>keyword.finish.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ambient|diffuse|brilliance|phong|phong_size|specular|roughness|metallic|reflection|crand|conserve_energy|reflection|irid)\b</string>
			<key>name</key>
			<string>keyword.finish-item.finish.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(fresnel|falloff|exponent|metallic)\b</string>
			<key>name</key>
			<string>keyword.reflection-item.finish.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(thickness|turbulence)\b</string>
			<key>name</key>
			<string>keyword.irid-item.finish.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(interior_texture)\b</string>
			<key>name</key>
			<string>keyword.interior-texture.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(texture_map)\b</string>
			<key>name</key>
			<string>keyword.texture-map.patterned-texture.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(tiles|tile2)\b</string>
			<key>name</key>
			<string>keyword.tile.patterned-texture.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(material_map)\b</string>
			<key>name</key>
			<string>keyword.material-map.patterned-texture.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(uv_mapping)\b</string>
			<key>name</key>
			<string>keyword.uv-mapping.patterned-texture.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cutaway_textures)\b</string>
			<key>name</key>
			<string>keyword.cataway-texture.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(average|boxed|bozo|bumps|cells|cylindrical|dents|function|gradient|granite|leopard|marble|onion|pigment_pattern|planar|radial|ripples|spherical|spiral1|spiral2|spotted|waves|wood|wrinkles)\b</string>
			<key>name</key>
			<string>keyword.map-pattern.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(agate)\b</string>
			<key>name</key>
			<string>keyword.agate.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(crackle)\b</string>
			<key>name</key>
			<string>keyword.crackle.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(from|metric|offset|solid)\b</string>
			<key>name</key>
			<string>keyword.crackle-type.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(density_file|df3)\b</string>
			<key>name</key>
			<string>keyword.density-file.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(facets)\b</string>
			<key>name</key>
			<string>keyword.facets.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(coords|size)\b</string>
			<key>name</key>
			<string>keyword.facets-type.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(mandel|exterior|interior)\b</string>
			<key>name</key>
			<string>keyword.mandelbrot-fractal.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(magnet|julia|exterior|interior)\b</string>
			<key>name</key>
			<string>keyword.magnet-julia-fractal.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(image_pattern)\b</string>
			<key>name</key>
			<string>keyword.image-pattern.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(use_alpha)\b</string>
			<key>name</key>
			<string>keyword.image-pattern-modifier.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(quilted|control0|control1)\b</string>
			<key>name</key>
			<string>keyword.quilted.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(slope|altitude)\b</string>
			<key>name</key>
			<string>keyword.slope.pattern.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(noise_generator)\b</string>
			<key>name</key>
			<string>keyword.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(turbulence|octaves|omega|lambda)\b</string>
			<key>name</key>
			<string>keyword.turbulence.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(warp)\b</string>
			<key>name</key>
			<string>keyword.warp.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(repeat|offset|flip)\b</string>
			<key>name</key>
			<string>keyword.repeat-warp.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(black_hole)\b</string>
			<key>name</key>
			<string>keyword.black-hole-warp.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(strength|falloff|inverse|repeat|turbulence)\b</string>
			<key>name</key>
			<string>keyword.black-hole-item.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cylindrical)\b</string>
			<key>name</key>
			<string>keyword.cylindrical-warp.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(toroidal|orientation|dist_exp|major_radius)\b</string>
			<key>name</key>
			<string>keyword.toroidal-warp.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(planar)\b</string>
			<key>name</key>
			<string>keyword.planar-warp.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(frequency|phase)\b</string>
			<key>name</key>
			<string>keyword.blend-map-modifier.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ramp_wave|triangle_wave|sine_wave|scallop_wave|cubic_wave|poly_wave)\b</string>
			<key>name</key>
			<string>keyword.waveform.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(agate_turb)\b</string>
			<key>name</key>
			<string>keyword.agate-modifier.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(brick_size|mortar)\b</string>
			<key>name</key>
			<string>keyword.brick-modifier.pattern-modifier.texture.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(interior)\b</string>
			<key>name</key>
			<string>keyword.interior.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ior|caustics|dispersion|dispersion_samples|fade_distance|fade_power|fade_color)\b</string>
			<key>name</key>
			<string>keyword.interior-item.interior.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(media)\b</string>
			<key>name</key>
			<string>keyword.media.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(method|intervals|samples|confidence|variance|ratio|absorption|emission|aa_threshold|aa_level|collect)\b</string>
			<key>name</key>
			<string>keyword.media-item.media.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(scattering|eccentricity|extinction)\b</string>
			<key>name</key>
			<string>keyword.scattering.media.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(density)\b</string>
			<key>name</key>
			<string>keyword.density.media.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(brick|checker|hexagon|object)\b</string>
			<key>name</key>
			<string>keyword.density-list-pattern.media.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(density_map)\b</string>
			<key>name</key>
			<string>keyword.density-map.media.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(photons)\b</string>
			<key>name</key>
			<string>keyword.photons.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(spacing|count|gather|media|jitter|max_trace_level|abc_bailout|save_file|load_file|autostop|expand_thresholds|radius)\b</string>
			<key>name</key>
			<string>keyword.global-photon-block.photons.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(background)\b</string>
			<key>name</key>
			<string>keyword.background.atmospheric-effect.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(fog|fog_type)\b</string>
			<key>name</key>
			<string>keyword.constant-fog.fog.atmospheric-effect.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(fog_offset|fog_alt|up|turb_depth|distance|turbulence|omega|lambda|octaves|)\b</string>
			<key>name</key>
			<string>keyword.ground-fog-item.fog.atmospheric-effect.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sky_sphere)\b</string>
			<key>name</key>
			<string>keyword.sky-sphere.atmospheric-effect.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(rainbow)\b</string>
			<key>name</key>
			<string>keyword.rainbow.atmospheric-effect.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(direction|angle|width|distance|jitter|up|arc_angle|falloff_angle)\b</string>
			<key>name</key>
			<string>keyword.rainbow-item.atmospheric-effect.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(global_settings)\b</string>
			<key>name</key>
			<string>keyword.global-setting.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(adc_bailout|ambient_light|assumed_gamma|hf_gray_16|irid_wavelength|charset|max_intersections|max_trace_level|number_of_waves|noise_generator)\b</string>
			<key>name</key>
			<string>keyword.global-setting-item.global-setting.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(radiosity)\b</string>
			<key>name</key>
			<string>keyword.radiosity.global-setting.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abc_bailout|always_sample|brightness|count|error_bound|gray_threshold|load_file|low_error_factor|max_sample|media|minimum_reuse|nearest_count|normal|pretrace_end|pretrace_start|recursion_limit|save_file)\b</string>
			<key>name</key>
			<string>keyword.radiosity-item.global-setting.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(photons)\b</string>
			<key>name</key>
			<string>keyword.photon.global-setting.povray</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.povray</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*/.*\n</string>
			<key>name</key>
			<string>invalid.illegal.stray-comment-end.povray</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.toc-list.banner.line.povray</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^//=(\s*.*?)\s*=\s*$
?</string>
			<key>name</key>
			<string>comment.line.banner.povray</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.povray</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.povray</string>
	<key>uuid</key>
	<string>a63dfc36-c4f6-4211-84b2-ec481d2fcaf9</string>
</dict>
</plist>
